spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/foryoufamily
    username: foryoufamily
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        # use_sql_comments: true
    open-in-view: false

config:
  jwt:
    secretKey: 01234567890123456789012345678912
    validTime: 30 # minutes

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace