server:
  port: ${PORT:8000}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} # eureka에서 인식할 instance id

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:eureka-server}:${EUREKA_SERVER_PORT:8761}/eureka # eureka server 가 위치하고 있는 기본 주소

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: JwtGlobalFilter
          args:
            baseMessage: GateWay JwtGlobalFilter
      routes:
        - id: member-api
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/**,/auth/**
#          filters:
#            - name: MemberFilter
#              args:
#                baseMessage: GateWay MemberFilter
#                excludePath: /member /member/login # 여러개 적을 경우 공백으로 띄어서
#                requiredRole: ROLE_MEMBER # 한개만 작성
        - id: party-api
          uri: lb://PARTY-API
          predicates:
            - Path=/party/**

config:
  jwt:
    secretKey: 01234567890123456789012345678912