server:
  port: ${PORT:8094}

spring:
  application:
    name: auth-api

  profiles:
    active: prod

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} # eureka가 인식할 instance id

logging.level:
  org.hibernate.SQL: debug