server:
  port: 8093

spring:
  application:
    name: billing-api

  datasource:
    url: jdbc:h2:tcp://localhost:1521/billingapi
    username: billingapi
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # use_sql_comments: true
    open-in-view: false

config:
  iamport:
    apikey: 9126903185453032
    apisecret: 21846cf8f313caf697b8909fc177d46f879c92c94439585bb9156172884c36bfd66caa96cf5329ff
  cipher:
    aesKey: abcdefghijklmnopabcdefghijklmnop #32Bytes
    iv: abcdefghijklmnop #16Bytes