server:
  port: ${PORT:8093}

spring:
  application:
    name: billing-api

  datasource:
    url: jdbc:h2:tcp://localhost:1521/billingapi
    username: billingapi
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # use_sql_comments: true
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_NAME1:localhost}:${KAFKA_SERVER_PORT1:9093}, ${KAFKA_SERVER_NAME2:localhost}:${KAFKA_SERVER_PORT2:9094}, ${KAFKA_SERVER_NAME3:localhost}:${KAFKA_SERVER_PORT3:9095}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} # eureka instance id

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:localhost}:${EUREKA_SERVER_PORT:8761}/eureka # eureka server 가 위치하고 있는 기본 주소

config:
  iamport:
    apikey: 9126903185453032
    apisecret: 21846cf8f313caf697b8909fc177d46f879c92c94439585bb9156172884c36bfd66caa96cf5329ff
  cipher:
    aesKey: abcdefghijklmnopabcdefghijklmnop #32Bytes
    iv: abcdefghijklmnop #16Bytes