spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: foryou-family
    password: foryou-family
    url: jdbc:mysql://43.200.243.244:3306/foryou_family?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false
    #        use_sql_comments: true
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER_NAME1:43.200.243.244}:${KAFKA_SERVER_PORT1:9093}, ${KAFKA_SERVER_NAME2:43.200.243.244}:${KAFKA_SERVER_PORT2:9094}, ${KAFKA_SERVER_NAME3:43.200.243.244}:${KAFKA_SERVER_PORT3:9095}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_NAME:43.200.243.244}:${EUREKA_SERVER_PORT:8761}/eureka # eureka server 가 위치하고 있는 기본 주소

config:
  iamport:
    apikey: 9126903185453032
    apisecret: 21846cf8f313caf697b8909fc177d46f879c92c94439585bb9156172884c36bfd66caa96cf5329ff
  cipher:
    aesKey: abcdefghijklmnopabcdefghijklmnop #32Bytes
    iv: abcdefghijklmnop #16Bytes