server:
  port: 8091

spring:
  application:
    name: party-api

  datasource:
    url: jdbc:h2:tcp://localhost/~/partyapi
    username: partyapi
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        # use_sql_comments: true
    open-in-view: false