server:
  port: ${PORT:8092}

spring:
  application:
    name: matching-service

  profiles:
    active: local

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port} # eureka가 인식할 instance id

logging.level:
  org.hibernate.SQL: debug